"""
higgsfield.py — Cloud AI video generation via the Higgsfield platform API.

Counterpart to comfy.py for machines without a GPU: instead of a local ComfyUI
server, scenes are generated by Higgsfield's hosted models (Seedance, Kling,
Veo, …) at https://platform.higgsfield.ai. This costs credits per clip, so it
is off by default and only used when enabled AND both API keys are present.
If anything fails (no keys, bad model id, moderation, timeout), every call
returns None and the caller falls back to the normal background path —
nothing breaks.

Auth: HIGGSFIELD_API_KEY + HIGGSFIELD_API_SECRET from the environment
(.env or keys/higgsfield_api_key + keys/higgsfield_api_secret).
Flow: POST /{model_id}, poll /requests/{request_id}/status, download video.url.
"""
import logging
import os
import time

import requests

log = logging.getLogger("studio.higgsfield")

BASE_URL = "https://platform.higgsfield.ai"


def _conf(cfg):
    return cfg.get("higgsfield") or {}


def _keys():
    return os.environ.get("HIGGSFIELD_API_KEY"), os.environ.get("HIGGSFIELD_API_SECRET")


def is_enabled(cfg):
    return bool(_conf(cfg).get("enabled"))


def is_available(cfg):
    """True if enabled AND both API keys are set. No network probe: the API is
    a paid queue, so availability is decided by config alone and real errors
    surface (and fall back) on the first generation call."""
    if not is_enabled(cfg):
        return False
    key, secret = _keys()
    return bool(key and secret)


def pick_duration(seconds, choices):
    """Map a scene duration to the smallest allowed model duration that covers
    it (assemble trims), else the largest available (assemble loops/slows)."""
    opts = sorted(int(c) for c in (choices or [5, 10]))
    for c in opts:
        if c >= seconds:
            return c
    return opts[-1]


def generate_clip(cfg, prompt, out_path, duration=5.0, on_progress=None):
    """Generate one text-to-video clip. Returns out_path or None on failure."""
    if not is_available(cfg):
        return None
    conf = _conf(cfg)
    key, secret = _keys()
    model = conf.get("model", "bytedance/seedance/v1/lite/text-to-video").strip("/")
    headers = {
        "Authorization": f"Key {key}:{secret}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    payload = {
        "prompt": prompt,
        "aspect_ratio": conf.get("aspect_ratio", "9:16"),
        "resolution": conf.get("resolution", "720p"),
        "duration": pick_duration(duration, conf.get("durations")),
    }
    # model-specific extras (e.g. quality, motion strength) pass through as-is
    payload.update(conf.get("params") or {})

    try:
        r = requests.post(f"{BASE_URL}/{model}", json=payload, headers=headers, timeout=30)
        r.raise_for_status()
        job = r.json()
    except Exception as e:
        log.warning("higgsfield submit failed: %s", e)
        return None

    status_url = job.get("status_url")
    if not status_url:
        rid = job.get("request_id")
        if not rid:
            log.warning("higgsfield: no request id in response: %s", job)
            return None
        status_url = f"{BASE_URL}/requests/{rid}/status"

    poll = float(conf.get("poll_seconds", 5))
    deadline = time.time() + float(conf.get("timeout_seconds", 600))
    while True:
        if time.time() > deadline:
            log.warning("higgsfield: timed out waiting for %s", status_url)
            return None
        try:
            s = requests.get(status_url, headers=headers, timeout=30)
            s.raise_for_status()
            job = s.json()
        except Exception as e:
            log.warning("higgsfield status poll failed: %s", e)
            return None
        status = (job.get("status") or "").lower()
        if status == "completed":
            break
        if status in ("failed", "nsfw", "cancelled"):
            # failed/nsfw refund credits on Higgsfield's side
            log.warning("higgsfield job ended as %r", status)
            return None
        if on_progress:
            on_progress(f"Higgsfield: {status or 'wartet'}…")
        time.sleep(poll)

    video = job.get("video") or {}
    url = video.get("url") if isinstance(video, dict) else None
    if not url:
        log.warning("higgsfield: completed but no video url: %s", job)
        return None
    try:
        from pipeline.atomicio import atomic_write_bytes

        with requests.get(url, stream=True, timeout=120) as dl:
            dl.raise_for_status()
            # Atomic: this used to swallow the exception and return None while
            # leaving a truncated mp4 at out_path for the caller to trip over.
            atomic_write_bytes(out_path, dl.iter_content(chunk_size=1 << 16))
    except Exception as e:
        log.warning("higgsfield download failed: %s", e)
        return None
    return out_path
